### ISSUE TITLE
Improve UI For mentor Section

### ISSUE THREAD

**Issue by manitesharma** [jboss-outreach/gci#33]
you can use this for reference :
![screenshot from 2017-11-04 19-48-57](https://user-images.githubusercontent.com/23737323/32406188-c4897c8c-c199-11e7-8e55-c2cad75fb88b.png)

**Comment by shubhamvashisht** [comment]
@garg-anuj  looks cool. what say?

**Comment by garg-anuj** [comment]
@manitesharma @shubhamvashisht  its nice. we should update it for all sections

**Comment by garg-anuj** [comment]
@manitesharma Any update on it?
