### ISSUE TITLE
Broken Link in GCI website

### ISSUE THREAD

**Issue by SachinRammoorthy** [jboss-outreach/gci#43]
Currently, when "Blog" is clicked on the [GCI website](https://github.com/jboss-outreach/gci), the user is led to https://jboss-outreach.github.io/blog, which does not exist.

It should instead, lead [here](https://blog.jboss-outreach.org/). [This PR](https://github.com/jboss-outreach/gci/pull/41) fixes this issue.

**Comment by zwliew** [comment]
Could you close this issue, now that the PR has been merged?

**Comment by SachinRammoorthy** [comment]
good idea 👍
