### ISSUE TITLE
Bug/Issue Top Horizontal Navigation Bar and incorrect scroll (local redirect)

### ISSUE THREAD

**Issue by divyanshkul** [jboss-outreach/gci#46]
I have found the following bugs in the Horizontal navigation bar while going through the Jboss Community GCI 2017 website:
* The background highlighting of the headigs are not proper:	
	       
	Cases:	
	- The highlighting head is always applied to the earlier clicked head. Eg. if I click on contributors and then click on mentors, the highlight wil be applied to the mentors head.
	- Clicking on the issues head, the welcome head always gets highlighted.
	- The background highlighting works perfectly in the mobile version except for the part that it does not keep the head highlighted after closing the navigation bar.
	- Sometimes, the default highlight is always set to welcome.

* The redirect on clicking the head is not proper:
	-  The students redirect is not proper, it still scrolls upto the contributors section only (maybe because of the default scroll set)
	-  On the contributors redirect, the heading "Contributors" gets overlapped by the navigation bar.
* Also, as pointed out in #42 the contributors section displays only the contributions of this repository not other Jboss-Outreach repositories. (this can easily be fixed by changing call url API at [line 204](https://github.com/jboss-outreach/gci/pull/41/commits/a747fead46592899177e196bc847dd9537fb7345#diff-6db0a6d80ceb8439f15acfa619f78de3R204) of main.js file

__How to solve__ : modifying the ``` class = "on click active" ``` javascript code and syncing it with the``` heading <div>```

**Comment by m-murad** [comment]
Can you send a PR fixing these issues?

**Comment by SachinRammoorthy** [comment]
@divyanshkul now that this issue has been fixed, can you close this issue?
