### ISSUE TITLE
Add a proper Footer 

### ISSUE THREAD

**Issue by aashutoshrathi** [jboss-outreach/gci#76]
Add a Footer to the GCI site having Projects of JBoss, all quick links, social media icons and copyright of JBoss and more can be proposed comment on this issue.

**Comment by divyanshkul** [comment]
Working on this. :)

**Comment by aashutoshrathi** [comment]
Assigned to @divyanshkul.

**Comment by aashutoshrathi** [comment]
Fire PR Soon

**Comment by divyanshkul** [comment]
Almost done, sorry for delay, will make the PR by tonight. :)

**Comment by SachinRammoorthy** [comment]
Now that the PR has been merged, perhaps this issue could be closed?
