### ISSUE TITLE
Improvements to the Profile Card

### ISSUE THREAD

**Issue by aashutoshrathi** [jboss-outreach/gci#77]
- `Information of` text from the card can be removed, it is redundant and ugly.
- Social media Icon can also be added to the card, as per link given or not.
- A bit of transparency on card won't hurt.
- Cards edges should be a little round.
- In some cases, picture and text are getting mixed, so margins can be improved.

This issue is open to more suggestion, comment below to let the issue taker know.

**Comment by SachinRammoorthy** [comment]
Working on this now.
