### ISSUE TITLE
Page Not Found + Travis Review

### ISSUE THREAD

**Issue by SachinRammoorthy** [jboss-outreach/gci#81]
The auto-deploy of a PR in this repo often does not show up, instead replaced with a _Page Not Found error_. 

This could possibly be linked to the Travis review of the PR, which takes a long time. I have noticed that the error shows up when a review is not complete, but this is not always the case.

![screen shot 2017-12-31 at 10 48 08 pm](https://user-images.githubusercontent.com/20569603/34463293-db75d534-ee7c-11e7-8aa7-d70e7a40674a.png)

**Comment by zwliew** [comment]
I don't think the 2 CIs aren't affected by one another.

**Comment by SachinRammoorthy** [comment]
No, me neither. I think the auto-deploy is linked to the _Codacy_ review, not Travis.

**Comment by zwliew** [comment]
The Travis CI is what auto deploys the PR :P

**Comment by SachinRammoorthy** [comment]
Oh. I'll change the title in that case :P 
I never doubted that the Travis and Codacy are **not** affected by one another. I meant that that the auto-deploy is linked to the Codacy review, but now that I know its Travis, I'll change the title 😆

**Comment by zwliew** [comment]
I took a look at this, and feel that the issue might just be a limitation with GitHub Pages. All Travis does is commit the HEAD to https://github.com/jboss-outreach-ibot/gci-autodeploy, and GitHub Pages would automatically load the static website up. In some cases, GitHub Pages might be a little slow, resulting in this issue.

**Comment by SachinRammoorthy** [comment]
Alright then, I'll close the issue.
